name: INE-bootcamp
channels:
    - intel
    - conda-forge
dependencies:
    - python=3.9
    - pip
    - numpy
    - pandas
    - matplotlib
    - seaborn
    - requests
    - scikit-learn
    - tabulate
    - xlrd
    - pip:
      - pyarrow
